# CI 파이프라인: 코드 품질 검증 및 배포 가능한 아티팩트(Docker 이미지) 생성

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'my-fastapi-service'
  _REGION: 'asia-northeast3'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker image
    args: 
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/tripout-repo/${_SERVICE_NAME}:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker image
    args: 
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/tripout-repo/${_SERVICE_NAME}:$SHORT_SHA'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/tripout-repo/${_SERVICE_NAME}:$SHORT_SHA'